
@baseUrl=http://localhost:3000/api
@resourceName=categories

# @name get
GET {{baseUrl}}/{{resourceName}}

###

# @name add
POST {{baseUrl}}/{{resourceName}}
Content-Type: application/json

{
  "name": "Laptop"
}

###

# @name patch
PATCH {{baseUrl}}/{{resourceName}}/2
Content-Type: application/json

{
  "name": "Laptop New"
}

###

# @name remove
DELETE {{baseUrl}}/{{resourceName}}/2
